defmodule AgentSos.Repo.Migrations.CreateAgentsTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:agents) do
      remove(:organisation_id)
      remove(:active)
      remove(:max_tokens)
      remove(:temperature)
      remove(:tools)
      remove(:provider)
      remove(:model)
      remove(:system_prompt)
      add(:adapter_type, :text, null: false)
      add(:adapter_config, :map, default: %{})
      add(:status, :text, null: false, default: "idle")
      add(:heartbeat_schedule, :text)
      add(:monthly_budget_cents, :bigint, default: 0)
      add(:budget_used_cents, :bigint, default: 0)
      add(:last_heartbeat_at, :utc_datetime_usec)
      add(:next_heartbeat_at, :utc_datetime_usec)

      add(
        :company_id,
        references(:organisations,
          column: :id,
          name: "agents_company_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :parent_agent_id,
        references(:agents,
          column: :id,
          name: "agents_parent_agent_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:agents, "agents_company_id_fkey"))

    drop(constraint(:agents, "agents_parent_agent_id_fkey"))

    alter table(:agents) do
      remove(:parent_agent_id)
      remove(:company_id)
      remove(:next_heartbeat_at)
      remove(:last_heartbeat_at)
      remove(:budget_used_cents)
      remove(:monthly_budget_cents)
      remove(:heartbeat_schedule)
      remove(:status)
      remove(:adapter_config)
      remove(:adapter_type)
      add(:system_prompt, :text, null: false, default: "You are a helpful assistant.")
      add(:model, :text, null: false, default: "claude-sonnet-4-20250514")
      add(:provider, :text, null: false, default: "anthropic")
      add(:tools, {:array, :map}, default: [])
      add(:temperature, :float, default: 0.7)
      add(:max_tokens, :bigint, default: 4096)
      add(:active, :boolean, default: true)

      add(
        :organisation_id,
        references(:organisations,
          column: :id,
          name: "agents_organisation_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end
  end
end
