defmodule AgentSos.Repo.Migrations.CreateIssuesAndRuns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:issues, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:title, :text, null: false)
      add(:description, :text)
      add(:status, :text, null: false, default: "open")
      add(:priority, :text, null: false, default: "medium")
      add(:checked_out_at, :utc_datetime_usec)
      add(:checked_out_by_run_id, :uuid)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :company_id,
        references(:organisations,
          column: :id,
          name: "issues_company_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :assignee_id,
        references(:agents,
          column: :id,
          name: "issues_assignee_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create table(:heartbeat_runs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:status, :text, null: false, default: "queued")
      add(:trigger_type, :text, null: false)
      add(:started_at, :utc_datetime_usec)
      add(:completed_at, :utc_datetime_usec)
      add(:tokens_used, :bigint)
      add(:cost_cents, :bigint)
      add(:duration_ms, :bigint)
      add(:stdout_log, :text)
      add(:error_message, :text)
      add(:jwt_jti, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :agent_id,
        references(:agents,
          column: :id,
          name: "heartbeat_runs_agent_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :company_id,
        references(:organisations,
          column: :id,
          name: "heartbeat_runs_company_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end
  end

  def down do
    drop(constraint(:heartbeat_runs, "heartbeat_runs_agent_id_fkey"))

    drop(constraint(:heartbeat_runs, "heartbeat_runs_company_id_fkey"))

    drop(table(:heartbeat_runs))

    drop(constraint(:issues, "issues_company_id_fkey"))

    drop(constraint(:issues, "issues_assignee_id_fkey"))

    drop(table(:issues))
  end
end
