defmodule AgentSos.Repo.Migrations.CreateGoalsApprovalsSecretsTemplates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:secrets, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:value, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :company_id,
        references(:organisations,
          column: :id,
          name: "secrets_company_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :agent_id,
        references(:agents,
          column: :id,
          name: "secrets_agent_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create table(:projects, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:description, :text)
      add(:status, :text, default: "planning")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :company_id,
        references(:organisations,
          column: :id,
          name: "projects_company_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(:goal_id, :uuid)
    end

    create table(:goals, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:projects) do
      modify(
        :goal_id,
        references(:goals,
          column: :id,
          name: "projects_goal_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:goals) do
      add(:title, :text, null: false)
      add(:description, :text)
      add(:status, :text, default: "active")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :company_id,
        references(:organisations,
          column: :id,
          name: "goals_company_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :parent_goal_id,
        references(:goals,
          column: :id,
          name: "goals_parent_goal_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create table(:company_templates, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:description, :text)
      add(:config, :map, default: %{})
      add(:is_public, :boolean, default: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:approvals, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:type, :text, null: false)
      add(:status, :text, default: "pending")
      add(:reason, :text)
      add(:decided_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :company_id,
        references(:organisations,
          column: :id,
          name: "approvals_company_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :agent_id,
        references(:agents,
          column: :id,
          name: "approvals_agent_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :requester_id,
        references(:users,
          column: :id,
          name: "approvals_requester_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(
        :decided_by_id,
        references(:users,
          column: :id,
          name: "approvals_decided_by_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:approvals, "approvals_company_id_fkey"))

    drop(constraint(:approvals, "approvals_agent_id_fkey"))

    drop(constraint(:approvals, "approvals_requester_id_fkey"))

    drop(constraint(:approvals, "approvals_decided_by_id_fkey"))

    drop(table(:approvals))

    drop(table(:company_templates))

    drop(constraint(:goals, "goals_company_id_fkey"))

    drop(constraint(:goals, "goals_parent_goal_id_fkey"))

    alter table(:goals) do
      remove(:parent_goal_id)
      remove(:company_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:status)
      remove(:description)
      remove(:title)
    end

    drop(constraint(:projects, "projects_goal_id_fkey"))

    alter table(:projects) do
      modify(:goal_id, :uuid)
    end

    drop(table(:goals))

    drop(constraint(:projects, "projects_company_id_fkey"))

    drop(table(:projects))

    drop(constraint(:secrets, "secrets_company_id_fkey"))

    drop(constraint(:secrets, "secrets_agent_id_fkey"))

    drop(table(:secrets))
  end
end
